auto_auth/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as contrib_auth_views
from django.contrib.auth.decorators import login_required
from auto_auth import views

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/profile/$', views.profile,
        name='auto-profile'),

    url(r'^register/$', views.register, name='auto-register'),

    url(r'^confirm/(?P<activation_key>[A-Za-z0-9\-]+)/$', views.confirm,
        name='auto-confirm'),

    url(r'^user/add/$', views.add_user, name='adduser'),
    url(r'^user/list/$', login_required(views.UserListIndex.as_view()), name='userlist'),
    url(r'^user/update/$', views.update_user, name='userupdate'),
    url(r'^user/del/(?P<id>\d+)/$', views.del_user, name='userdel'),
    url(r'^setedit/user/$', views.set_edit_user, name='setedituser'),

    url(r'^login/$', views.LoginViewWithCustomTemplate.as_view(), name='auto-login'),
    url(r'^logout/$',
        contrib_auth_views.LogoutView.as_view(next_page=reverse_lazy('auto-login')),
        name='auto-logout'),

    url(r'^passwordreset/$', contrib_auth_views.PasswordResetView.as_view(),
        name='auto-password_reset'),
    url(r'^passwordreset/done/$', contrib_auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^passwordreset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        contrib_auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^passwordreset/complete/$',
        contrib_auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

automatic/element/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from automatic.element import views

urlpatterns = [
    url(r'list/$', login_required(views.ElementListIndex.as_view()), name='elementlist'),
    url(r'add/$', views.add_element, name='elementadd'),
    url(r'update/$', views.update_element, name='elementupdate'),
    url(r'del/(?P<id>\d+)/$', views.del_element, name='elementdel'),
    url(r'get/$', views.get_element, name='getelement'),
    url(r'setedit/$', views.set_edit_element, name='seteditelement'),
]

automatic/keywords/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from automatic.keywords import views

urlpatterns = [
    url(r'list/$', login_required(views.KeyWordListIndex.as_view()), name='keywordlist'),
    url(r'add/$', views.add_keyword, name='keywordadd'),
    url(r'update/$', views.update_keyword, name='keywordupdate'),
    url(r'del/(?P<id>\d+)/$', views.del_keyword, name='keyworddel'),
    url(r'get/$', views.get_keyword, name='getkeyword'),
    url(r'setedit/$', views.set_edit_keyword, name='seteditelement'),
]

automatic/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include, url
from auto_auth import urls as auth_urls
from automatic.testcase import urls as case_urls
from automatic.management import urls as mgt_urls
from automatic.element import urls as ele_urls
from automatic.keywords import urls as keywords_urls
from automatic.testtask import urls as task_urls
from automatic.webinterface import urls as interf_urls
from auto_auth.views import index

urlpatterns = [
    url('^$', index),
    url('^index/', index),
    url('admin/', admin.site.urls),
    url(r'^account/', include(auth_urls)),

    url(r'^setting/', include(mgt_urls)),

    url(r'^func/case/', include(case_urls)),

    url(r'^func/element/', include(ele_urls)),

    url(r'^func/keyword/', include(keywords_urls)),

    url(r'^func/task/', include(task_urls)),

    url(r'^interface/', include(interf_urls)),



    # url(r'^interf/web/home/$',  login_required(interface.WebinterfaceListIndex.as_view()), name='webinterface'),
    # url(r'^interf/get/response/$', interface.get_response, name='getresponse'),
    # url(r'^tools/syslog/home/$', automate.page_syslog, name='toolsyslog'),
    # url(r'^tools/snmp/home/$', automate.comingsoon, name='toolsnmp'),
    # url(r'^accounts/', include(oidc_urls)),
]

automatic/testtask/models.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-06
"""
from django.db import models
from automatic.management.models import Project, User
# Create your models here.


class Task(models.Model):
    Task_Choice = (
        ('1', '执行用例'),
        ('2', '用例同步'),
        ('3', '关联Jenkins'),
    )
    taskname = models.CharField(max_length=255,verbose_name="任务描述")
    tasktype = models.CharField(max_length=32, choices=Task_Choice, blank=True, editable=True)
    status = models.SmallIntegerField(default=0, verbose_name='任务状态')
    issmoke = models.BooleanField(default=False)
    testrailsuites = models.CharField(max_length=8, verbose_name='TestRail测试集ID', null=True, blank=True, editable=True)
    testrailrunid = models.CharField(max_length=8,verbose_name='TestRail执行ID',null=True,blank=True, editable=True)
    testsectionid = models.CharField(max_length=8, verbose_name='TestRail用例节点ID',null=True,blank=True, editable=True)
    projectid = models.ForeignKey(Project, on_delete=models.DO_NOTHING)
    jenkins_server_url = models.CharField(max_length=100, verbose_name='JenkinsServer', null=True, blank=True, editable=True)
    user_id = models.CharField(max_length=32, verbose_name='JenkinsUserid', null=True, blank=True, editable=True)
    api_token = models.CharField(max_length=32, verbose_name='JenkinsApitoken', null=True, blank=True, editable=True)
    build_name = models.CharField(max_length=32, verbose_name='JenkinsBuildName', null=True, blank=True, editable=True)
    caselist = models.CharField(max_length=10240, verbose_name='用例列表')
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now=True)
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)

    def __unicode__(self):
        return  self.taskname

class Codelist(models.Model):
    taskid = models.ForeignKey(Task, on_delete=models.DO_NOTHING)
    codename = models.CharField(max_length=32)
    codedescr = models.CharField(max_length=255)
    codevalue = models.CharField(max_length=255)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now=True)
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.codename

class Taskhistory(models.Model):
    taskid = models.ForeignKey(Task, on_delete=models.DO_NOTHING)
    userid = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    tasktype = models.CharField(max_length=32, blank=True, editable=True)
    taskname = models.CharField(max_length=255, verbose_name="任务描述")
    case_tag_all = models.CharField(max_length=8, null=True, blank=True, editable=True)
    case_tag_pass = models.CharField(max_length=8, null=True, blank=True, editable=True)
    case_tag_fail = models.CharField(max_length=8, null=True, blank=True, editable=True)
    case_tag_error = models.CharField(max_length=8, null=True, blank=True, editable=True)
    starttime = models.DateTimeField(blank=True, editable=True)
    exectime = models.CharField(max_length=32, null=True, blank=True, editable=True)
    reporturl = models.CharField(max_length=255, verbose_name="report Url", null=True)
    build_name = models.CharField(max_length=32, null=True, blank=True, editable=True)
    build_number = models.CharField(max_length=8, null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.pk

automatic/element/forms.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-08
"""
from django import forms
from automatic.element.models import Element
from django.forms import ModelForm, Textarea, Select, TextInput


class FormElement(forms.ModelForm):
    class Meta:
        model = Element
        fields = ('descr','projectid','moduleid','locmode','location')
        widgets = {'locmode': Select(attrs={'class':'ak-left ac-aselect','required':''}),
                   'descr':TextInput(attrs={'class':'form-control','placeholder':'请输入元素描述','required':''}),
                   'location': TextInput(attrs={'class': 'form-control','placeholder':'（如：id_username）','required':''}),
                   }

automatic/element/views.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-08
"""
import json
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from automatic.element.forms import *
from django.views.generic import ListView
from automatic.element.models import *
from django.db.models import Q
from django.urls import reverse
from automatic.management.models import Project, UserAndProduct
from automatic.element.models import Element

# Create your views here.


class ElementListIndex(ListView):
    context_object_name = 'elementlist'
    template_name = 'element/element.html'
    paginate_by = 10
    elementsum = 0
    model = Element
    http_method_names = [u'get']

    def get_queryset(self):
        prodcutid = UserAndProduct.objects.filter(username=self.request.user).values('productname')
        elementlist = Element.objects.filter(projectid__in=Project.objects.filter(productid__in=prodcutid).values('id')).order_by('-pk')
        prodcutid = self.request.GET.get('check_productname')
        projectid = self.request.GET.get('projectid')
        moduleid = self.request.GET.get('moduleid')
        keyword = self.request.GET.get('keyword')
        if prodcutid and int(prodcutid):
            elementlist = elementlist.filter(projectid__in=Project.objects.filter(productid=prodcutid).values('id'))
        if projectid:
            elementlist = elementlist.filter(projectid=projectid)
        if moduleid:
            elementlist = elementlist.filter(moduleid=moduleid)
        if keyword:
            elementlist = elementlist.filter(Q(id__icontains=keyword)|Q(location__icontains=keyword)|Q(descr__icontains=keyword))
        self.elementsum = len(elementlist)
        return  elementlist

    def get_context_data(self, **kwargs):
        context = super(ElementListIndex,self).get_context_data(**kwargs)
        namelist = Element.objects.values('descr').annotate()
        context['descr'] = namelist
        context['elementsum'] = self.elementsum
        context['elementform'] = FormElement()
        context['userandproduct'] = UserAndProduct.objects.all()
        return context

@csrf_exempt
@login_required()
def add_element(request):
    if request.method == 'POST':
        descr = request.POST['descr']
        projectid = request.POST['projectid']
        moduleid = request.POST['moduleid']
        locmode = request.POST['locmode']
        location = request.POST['location']
        createat = request.user.username
        updateat = request.user.username
        mid = Module.objects.get(pk=int(moduleid))
        pid = Project.objects.get(pk=int(projectid))
        ele = Element(moduleid=mid, projectid=pid, descr=descr, locmode=locmode, location=location, createat=createat, updateat=updateat)
        ele.save()
        # return HttpResponse(descr + '@' + locmode + '@' + location + '@' + str(mid.pk))
        return HttpResponse('添加元素成功。')
    else:
        return HttpResponse('添加元素失败。')


@csrf_exempt
@login_required()
def update_element(request):
    if request.method == 'POST':
        post_dict = request.POST
        element_dict = {"id":post_dict['elementid'],
                        "descr": post_dict['eledescr'],
                        "projectid":post_dict['ele_add_projectid'],
                        "moduleid": post_dict['moduleid'],
                        "locmode": post_dict['locmode'],
                        "location": post_dict['elelocation'],
                        }
        id = element_dict.get('id')
        descr = element_dict.get('descr')
        projectid = element_dict.get('projectid')
        moduleid = element_dict.get('moduleid')
        locmode = element_dict.get('locmode')
        location = element_dict.get('location')
        updateat = request.user.username
        updatetime = timezone.now()
        e = Element.objects.filter(id=int(id))
        e.update(descr=descr, projectid=projectid,moduleid=moduleid,locmode=locmode, location=location,updateat=updateat,updatetime=updatetime)
        return HttpResponse('修改成功')
    else:
        return HttpResponse('修改失败')


@login_required()
def del_element(request, id):
    element = get_object_or_404(Element, pk=int(id))
    element.delete()
    return HttpResponseRedirect(reverse('elementlist'))


@login_required()
def get_element(request):
    elementlist = []
    projectid = request.GET['projectid']
    elelista = Element.objects.raw("select id,(select name from management_module where id= moduleid_id) as modulename,locmode,location,descr from element_element where projectid_id="+projectid)
    for i in elelista:
        element = {}
        element['moduleid'] = i.modulename
        element['key'] = i.id
        location = i.locmode + "," + i.location
        element['location'] = location
        element['value'] = "["+str(i.id)+"][" + i.modulename + "]" + i.descr
        elementlist.append(element)
    return HttpResponse(json.dumps(elementlist))


@login_required()
def set_edit_element(request):
    elementid = request.GET['elementid']
    element = Element.objects.get(pk=elementid)
    elementinfo = {}
    elementinfo['id'] = element.pk
    elementinfo['descr'] = element.descr
    elementinfo['projectid'] = element.projectid.pk
    elementinfo['moduleid'] = element.moduleid.pk
    elementinfo['locmode'] = element.locmode
    elementinfo['location'] = element.location
    elementlist = [elementinfo]
    return HttpResponse(json.dumps(elementlist))

automatic/keywords/views.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-08
"""
import json

from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from automatic.element.forms import *
from django.views.generic import ListView
from automatic.element.models import *
from django.db.models import Q
from django.urls import reverse
from automatic.management.models import Product, Project, UserAndProduct
from automatic.keywords.models import Keyword


class KeyWordListIndex(ListView):
    context_object_name = 'keywordlist'
    template_name = 'keywords/keyword.html'
    paginate_by = 10
    keywordsum = 0
    model = Keyword
    http_method_names = [u'get']

    def get_queryset(self):
        keywordlist = Keyword.objects.all().order_by('-pk')
        keyword = self.request.GET.get('keyword')
        if keyword:
            keywordlist = keywordlist.filter(Q(keyword__icontains=keyword)|Q(kwdescr__icontains=keyword))
        self.keywordsum = len(keywordlist)
        return  keywordlist

    def get_context_data(self, **kwargs):
        context = super(KeyWordListIndex,self).get_context_data(**kwargs)
        context['userandproduct'] = UserAndProduct.objects.all()
        context['productlist'] = Product.objects.all()
        context['keywordsum'] = self.keywordsum
        return context


@login_required()
def add_keyword(request):
    if request.method == 'POST':
        name = request.POST['keyword']
        descr = request.POST['kwdescr']
        productid = request.POST['productid']
        createat = request.user.username
        updateat = request.user.username
        keyword = Keyword(productid=productid, keyword=name, kwdescr=descr, createat=createat, updateat=updateat)
        try:
            keyword.save()
        except Exception as e:
            return HttpResponse(e)
        return HttpResponse('添加关键字成功。')
    else:
        return HttpResponse('添加关键字失败。')


@csrf_exempt
@login_required()
def update_keyword(request):
    if request.method == 'POST':
        id = request.POST['keywordid']
        name = request.POST['keyword']
        descr = request.POST['kwdescr']
        productid = request.POST['productname']
        updateat = request.user.username
        updatetime = timezone.now()
        k = Keyword.objects.filter(id=int(id))
        k.update(productid=productid, keyword=name, kwdescr=descr, updateat=updateat, updatetime=updatetime)
        return HttpResponse('修改关键字成功。')
    else:
        return HttpResponse('修改关键字失败。')


@login_required()
def del_keyword(request, id):
    keyword = get_object_or_404(Keyword, pk=int(id))
    keyword.delete()
    return HttpResponseRedirect(reverse('keywordlist'))


@login_required()
def get_keyword(request):
    keywordlist = []
    productid = request.GET['productid']
    kwlist = Keyword.objects.filter(Q(productid=productid)|Q(productid=0))
    for i in kwlist:
        keywordinfo = {}
        keywordinfo['key'] = i.id
        keywordinfo['kwdescr'] = i.kwdescr
        keywordinfo['keyword'] = i.keyword
        keywordinfo['productid'] = i.productid
        keywordlist.append(keywordinfo)
    return HttpResponse(json.dumps(keywordlist))


@login_required()
def set_edit_keyword(request):
    keywordid = request.GET['keywordid']
    kw = Keyword.objects.get(pk=keywordid)
    keywordinfo = {}
    keywordinfo['id'] = kw.pk
    keywordinfo['descr'] = kw.kwdescr
    keywordinfo['name'] = kw.keyword
    keywordinfo['productid'] = kw.productid
    keywordlist = [keywordinfo]
    return HttpResponse(json.dumps(keywordlist))

automatic/templates/testtask/taskadd.html
{% extends 'frame.html' %}
{% block title %}Automagic{% endblock %}
{% block slideshow %}

    <div class="ak-zper-midbox ak-jsch-mid">
        <div class="ak-zper-inbox-title ak-jsch-title clearfix">
            <div class="ak-left ak-jsch-row3 ak-zper-fix-btnbox">
                <span class="ak-zper-remindback"></span>
                <span class="inbox-text">添加任务</span>
            </div>
            <div id="log_info" class="ac-addtips"></div>
            <select id="selproductid" name="productname" class="ak-right ak-left ac-aselect ac-margint8">
                <option value="0">-产品名称-</option>
                {% for product in userandproduct %}
                    {% if product.username == request.user %}
                        <option value="{{ product.productname.id }}"
                                {% if request.GET.productname  == product.productname.name %}selected{% endif %}>{{ product.productname.name }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>

        <div class="col-md-12">
            <form method='post' id="task_add">
                {% csrf_token %}
                <div class="ak-jsch-modal-row col01">
                    <div class="ak-jsch-pos">
                        <div class="ak-jsch-point">
                        </div>
                    </div>
                    <div class="ak-jsch-modal-text col01 clearfix">
                        <span class="ak-jsch-item-left ak-left ">任务描述</span>
                        <div class="ak-jsch-item-right col02 ak-left">
                            <input id="id_taskname" name="taskname" class="ak-jsch-modal-input" type="text" required=""
                                   placeholder="任务描述">
                        </div>
                    </div>
                </div>
                <div class="ak-jsch-modal-row col01 ak-jsch-padding">
                    <div class="ak-jsch-modal-text">
                        <div class="ak-jsch-modal-item clearfix"><span class="ak-left ak-jsch-item-left ">任务类型</span>
                            <div style="margin-top:4px;">
                                <label>&nbsp&nbsp<input class="radioitem" id="runcase" type="radio" name="tasktype"
                                                        value="1" checked="checked">执行用例</label>
{#                                <label>&nbsp&nbsp<input class="radioitem" id="syncase" type="radio" name="tasktype"#}
{#                                                        value="2">同步用例</label>#}
                                <label>&nbsp&nbsp<input class="radioitem" id="connjenkins" type="radio" name="tasktype"
                                                        value="3">关联Jenkins</label>
                            </div>
                        </div>
                        <div class="ak-jsch-modal-item ak-jsch-pt clearfix ac-paddingt0">
{#                            <div id="testrailrunid" class="ak-jsch-modal-item clearfix"><span#}
{#                                    class="ak-left ak-jsch-item-left ">RunID&nbsp</span>#}
{#                                <input type="text" class="ac-acaseedit-input ac-margin110" name="testrailrunid">#}
{#                            </div>#}
                            <div class="ak-jsch-modal-item clearfix"><span
                                        class="ak-left ak-jsch-item-left ">用例类型</span>

                                        <select id="issmoke" name="issmoke" class="ak-left ac-aselect col01 ac-margin110"
                                        required="">
                                            <option value="0" selected>系统测试</option>
                                            <option value="1">冒烟测试</option>

                                </select>
                                </div>

                            <div id="testrailsuites" class="ak-jsch-modal-item clearfix" hidden="true"><span
                                    class="ak-left ak-jsch-item-left ">SuitesID&nbsp</span>
                                <input type="text" class="ac-acaseedit-input ac-margin110" name="testrailsuites">
                            </div>

                            <div id="testsectionid" class="ak-jsch-modal-item clearfix ac-margint10" hidden="true"><span
                                    class="ak-left ak-jsch-item-left ">SectionID&nbsp</span>
                                <input type="text" class="ac-acaseedit-input ac-margin110" name="testsectionid">
                            </div>
                            <div id="jenkins_server_url" class="ak-jsch-modal-item clearfix ac-margint10" hidden="true">
                                <span class="ak-left ak-jsch-item-left ">JenkinsURL&nbsp</span>
                                <input type="text" class="ac-acaseedit-input ac-margin110 ac-acode-desc"
                                       name="jenkins_server_url">
                            </div>
                            <div id="user_id" class="ak-jsch-modal-item clearfix ac-margint10" hidden="true"><span
                                    class="ak-left ak-jsch-item-left ">UserID&nbsp</span>
                                <input type="text" class="ac-acaseedit-input ac-margin110 ac-acode-desc" name="user_id">
                            </div>
                            <div id="api_token" class="ak-jsch-modal-item clearfix ac-margint10" hidden="true"><span
                                    class="ak-left ak-jsch-item-left ">ApiToken&nbsp</span>
                                <input type="text" class="ac-acaseedit-input ac-margin110 ac-acode-desc"
                                       name="api_token">
                            </div>
                            <div id="build_name" class="ak-jsch-modal-item clearfix ac-margint10" hidden="true"><span
                                    class="ak-left ak-jsch-item-left ">BuildName&nbsp</span>
                                <input type="text" class="ac-acaseedit-input ac-margin110 ac-acode-desc"
                                       name="build_name">
                            </div>
                        </div>
                        <div class="ak-jsch-modal-item ak-jsch-pt clearfix ac-paddingt0">
                            <span class="ak-jsch-item-left ak-left">项目</span>
                            <div class="ak-jsch-item-right ak-left">
                                <select id="selprojectid_task" name="projectid" class="ak-left ac-aselect col01"
                                        required="">
                                    <option value="0">所属项目</option>{% for i in  projectlist %}
                                    <option value="{{ i.pk }}">{{ i.name }}</option>{% endfor %}</select>
                            </div>
                        </div>
                        <div class="ak-jsch-modal-item ak-jsch-pt clearfix ac-paddingt0">
                            <div class="ak-jsch-item-right ak-left">
                                <ul id="treeDemo" class="ztree"
                                    style="height:350px; overflow:auto;font-family:verdana;border-radius:6px;border:2px solid #EE872A;"></ul>
                            </div>
                        </div>
                        <div class="ak-jsch-modal-item ak-jsch-pt clearfix" id="customParameters">
                            <h5><b>自定义参数</b></h5>
                            <div class="ak-jsch-item-right ak-left">
                                <ul style="height:300px; overflow:auto;font-family:verdana;border-radius:6px;border:1px solid #c1c1c1; ac-paddingt0">
                                    <table class="table" id="tab" style="width:72%">
                                        <caption class="text-left">
                                            <button type="button" onclick="addtr();"
                                                    class="text-left ac-btn-adduser blue ac-margin-tb15">添加一行
                                            </button>
                                            <input class="ac-acaseedit-input" id="rowid" value="" type="number"
                                                   placeholder="添加到第N行之后">
                                        </caption>
                                        <thead>
                                        <th>No</th>
                                        <th>描述</th>
                                        <th>参数编码</th>
                                        <th>参数值</th>
                                        <th>操作</th>
                                        <input hidden="true" id="linecounter" value=1 type='text'>
                                        </thead>
                                        <tbody>
                                        <tr id="row1">
                                            <td>1</td>
                                            <td><input name="codedescr" class="ac-acaseedit-input" placeholder="参数描述"
                                                       type="input"></td>
                                            <td><input name="codename" class="ac-acaseedit-input"
                                                       placeholder="参数编码(MWIP)" type="input"></td>
                                            <td><input name="codevalue" class="ac-acaseedit-input ac-acode-desc"
                                                       placeholder="参数值" type="input"></td>
                                            <td></td>
                                        </tr>
                                        </tbody>
                                        <tfoot class="text-left">

                                        </tfoot>
                                    </table>
                                </ul>
                            </div>
                        </div>
                        <div style="text-align: center;">
                            <input class="btn btn-sm btn-primary" type="submit" value="提交">
                            <input class="btn btn-sm btn-default" type="reset" value="重置">
                            <button onclick="goback();" class="btn btn-sm btn-success" role="button">返回>></button>
                        </div>
                    </div>
                </div>
                <input id="caseids" type="text" name="caseids" style="visibility:hidden" value="">
            </form>
        </div>
    </div>

{% endblock %}
{% block script %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/taskmanage.js' %}"></script>
    <script>
    $("#issmoke").bind("change", function () {
            var s1SelectedVal = $('#selprojectid_task').val();
            var issmoke = $('#issmoke').val();
            $.ajax({
                type: "GET",
                data: {'projectid': s1SelectedVal,'issmoke':issmoke},
                url: "/setting/get/moduleList/", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                cache: false,
                dataType: 'text',
                success: function (result, TextStatus) {
                    zNodes = eval(result)
                    $.fn.zTree.init($("#treeDemo"), setting, zNodes);
                    if ($("form#task_edit").length > 0) {
                        setTreeValue("{{ taskinfo.caselist}}");
                    }
                },
                error: function (result) {
                    alert(result)
                }

            });
        });
    </script>
{% endblock %}