auto_auth/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as contrib_auth_views
from django.contrib.auth.decorators import login_required
from auto_auth import views

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/profile/$', views.profile,
        name='auto-profile'),

    url(r'^register/$', views.register, name='auto-register'),

    url(r'^confirm/(?P<activation_key>[A-Za-z0-9\-]+)/$', views.confirm,
        name='auto-confirm'),

    url(r'^user/add/$', views.add_user, name='adduser'),
    url(r'^user/list/$', login_required(views.UserListIndex.as_view()), name='userlist'),
    url(r'^user/update/$', views.update_user, name='userupdate'),
    url(r'^user/del/(?P<id>\d+)/$', views.del_user, name='userdel'),
    url(r'^setedit/user/$', views.set_edit_user, name='setedituser'),

    url(r'^login/$', views.LoginViewWithCustomTemplate.as_view(), name='auto-login'),
    url(r'^logout/$',
        contrib_auth_views.LogoutView.as_view(next_page=reverse_lazy('auto-login')),
        name='auto-logout'),

    url(r'^passwordreset/$', contrib_auth_views.PasswordResetView.as_view(),
        name='auto-password_reset'),
    url(r'^passwordreset/done/$', contrib_auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^passwordreset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        contrib_auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^passwordreset/complete/$',
        contrib_auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

automatic/element/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from automatic.element import views

urlpatterns = [
    url(r'list/$', login_required(views.ElementListIndex.as_view()), name='elementlist'),
    url(r'add/$', views.add_element, name='elementadd'),
    url(r'update/$', views.update_element, name='elementupdate'),
    url(r'del/(?P<id>\d+)/$', views.del_element, name='elementdel'),
    url(r'get/$', views.get_element, name='getelement'),
    url(r'setedit/$', views.set_edit_element, name='seteditelement'),
]

automatic/keywords/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from automatic.keywords import views

urlpatterns = [
    url(r'list/$', login_required(views.KeyWordListIndex.as_view()), name='keywordlist'),
    url(r'add/$', views.add_keyword, name='keywordadd'),
    url(r'update/$', views.update_keyword, name='keywordupdate'),
    url(r'del/(?P<id>\d+)/$', views.del_keyword, name='keyworddel'),
    url(r'get/$', views.get_keyword, name='getkeyword'),
    url(r'setedit/$', views.set_edit_keyword, name='seteditelement'),
]

automatic/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include, url
from auto_auth import urls as auth_urls
from automatic.testcase import urls as case_urls
from automatic.management import urls as mgt_urls
from automatic.element import urls as ele_urls
from automatic.keywords import urls as keywords_urls
from automatic.testtask import urls as task_urls
from automatic.webinterface import urls as interf_urls
from auto_auth.views import index

urlpatterns = [
    url('^$', index),
    url('^index/', index),
    url('admin/', admin.site.urls),
    url(r'^account/', include(auth_urls)),

    url(r'^setting/', include(mgt_urls)),

    url(r'^func/case/', include(case_urls)),

    url(r'^func/element/', include(ele_urls)),

    url(r'^func/keyword/', include(keywords_urls)),

    url(r'^func/task/', include(task_urls)),

    url(r'^interface/', include(interf_urls)),



    # url(r'^interf/web/home/$',  login_required(interface.WebinterfaceListIndex.as_view()), name='webinterface'),
    # url(r'^interf/get/response/$', interface.get_response, name='getresponse'),
    # url(r'^tools/syslog/home/$', automate.page_syslog, name='toolsyslog'),
    # url(r'^tools/snmp/home/$', automate.comingsoon, name='toolsnmp'),
    # url(r'^accounts/', include(oidc_urls)),
]

automatic/element/models.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-06
"""
from django.db import models
from automatic.management.models import Project, Module
# Create your models here.

class Element(models.Model):
    Element_Choice = (
        ('id','id'),
        ('name','name'),
        ('css selector','css selector'),
        ('xpath','xpath'),
        ('class name','class name'),
        ('tag name','tag name'),
        ('link text','link text'),
        ('portial link_text','portial link text')
    )
    projectid = models.ForeignKey(Project, editable=True, on_delete=models.DO_NOTHING)
    moduleid = models.ForeignKey(Module, editable=True, on_delete=models.DO_NOTHING)
    descr = models.CharField(max_length=100, editable=True)
    locmode = models.CharField(max_length=32, choices=Element_Choice, null=True, blank=True, editable=True)
    location = models.CharField(max_length=200, null=True, blank=True, editable=True)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now=True)
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.descr

automatic/keywords/models.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-06
"""
from django.db import models
# Create your models here.


class Keyword(models.Model):
    productid = models.IntegerField(verbose_name='所属产品', null=True, blank=True, editable=True)
    keyword = models.CharField(max_length=32, unique=True)
    kwdescr = models.TextField(null=True,blank=True,editable=True)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now=True)
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.keyword

    class Meta:
        ordering = ["productid"]

automatic/management/models.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-06
"""
from __future__ import unicode_literals

import datetime
from django.db import models
from auto_auth.models import User
# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=32, verbose_name='产品名称', unique=True)
    # version = models.CharField(max_length=32)
    isenabled = models.BooleanField(default=True, blank=True, verbose_name='产品状态')
    descr = models.TextField(null=True, blank=True, verbose_name='产品描述')
    createtime = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='创建时间')
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='创建者')
    updatetime = models.DateTimeField(auto_now=True,null=True, blank=True, verbose_name='更新时间')
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='更新者')
    sortby = models.IntegerField(null=True, blank=True, editable=True, default=0, verbose_name='排序')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.createtime = datetime.datetime.now()
            self.updatetime = datetime.datetime.now()

        super(Product, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-sortby"]


class Project(models.Model):
    productid = models.ForeignKey(Product, verbose_name='产品名称', on_delete=models.CASCADE)
    name = models.CharField(max_length=32, unique=True, verbose_name='项目名称')
    version = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='版本')
    isenabled = models.BooleanField(default=True, verbose_name='状态')
    descr = models.TextField(null=True, blank=True, editable=True,verbose_name='项目描述')
    createtime = models.DateTimeField(auto_now_add=True, null=True, blank=True, editable=True,verbose_name='创建时间')
    createat = models.CharField( max_length=32, null=True, blank=True, editable=True, verbose_name='创建者')
    updatetime = models.DateTimeField(auto_now=True,null=True, blank=True, verbose_name='更新时间')
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='更新者')
    sortby = models.IntegerField(null=True, blank=True, editable=True, default=0, verbose_name='排序')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["-sortby"]


class Module(models.Model):
    projectid = models.ForeignKey(Project, verbose_name='所属项目', on_delete=models.CASCADE)
    name = models.CharField(max_length=32, verbose_name='模块名称')
    isenabled = models.BooleanField(default=True, verbose_name='状态')
    createtime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    createat = models.CharField(max_length=32 ,null=True, blank=True, editable=True, verbose_name='创建者')
    updatetime = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='更新者')
    sortby = models.IntegerField(null=True, blank=True, editable=True, default=0, verbose_name='排序')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["-sortby"]

class UserAndProduct(models.Model):
    username = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    productname = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

automatic/element/forms.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-08
"""
from django import forms
from automatic.element.models import Element
from django.forms import ModelForm, Textarea, Select, TextInput


class FormElement(forms.ModelForm):
    class Meta:
        model = Element
        fields = ('descr','projectid','moduleid','locmode','location')
        widgets = {'locmode': Select(attrs={'class':'ak-left ac-aselect','required':''}),
                   'descr':TextInput(attrs={'class':'form-control','placeholder':'请输入元素描述','required':''}),
                   'location': TextInput(attrs={'class': 'form-control','placeholder':'（如：id_username）','required':''}),
                   }

automatic/testcase/forms.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-06
"""
from django import forms
from automatic.testcase.models import *


class FormCase(forms.ModelForm):
    class Meta:
        model = Case
        fields = ('casedesc','testrailcaseid','projectid','moduleid','isenabled','dependent')


class FormStep(forms.ModelForm):
    class Meta:
        model = Step
        fields = ('caseid', 'descr', 'keywordid','elementid','inputtext')

automatic/element/views.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-08
"""
import json
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from automatic.element.forms import *
from django.views.generic import ListView
from automatic.element.models import *
from django.db.models import Q
from django.urls import reverse
from automatic.management.models import Project, UserAndProduct
from automatic.element.models import Element

# Create your views here.


class ElementListIndex(ListView):
    context_object_name = 'elementlist'
    template_name = 'element/element.html'
    paginate_by = 10
    elementsum = 0
    model = Element
    http_method_names = [u'get']

    def get_queryset(self):
        prodcutid = UserAndProduct.objects.filter(username=self.request.user).values('productname')
        elementlist = Element.objects.filter(projectid__in=Project.objects.filter(productid__in=prodcutid).values('id')).order_by('-pk')
        prodcutid = self.request.GET.get('check_productname')
        projectid = self.request.GET.get('projectid')
        moduleid = self.request.GET.get('moduleid')
        keyword = self.request.GET.get('keyword')
        if prodcutid and int(prodcutid):
            elementlist = elementlist.filter(projectid__in=Project.objects.filter(productid=prodcutid).values('id'))
        if projectid:
            elementlist = elementlist.filter(projectid=projectid)
        if moduleid:
            elementlist = elementlist.filter(moduleid=moduleid)
        if keyword:
            elementlist = elementlist.filter(Q(id__icontains=keyword)|Q(location__icontains=keyword)|Q(descr__icontains=keyword))
        self.elementsum = len(elementlist)
        return  elementlist

    def get_context_data(self, **kwargs):
        context = super(ElementListIndex,self).get_context_data(**kwargs)
        namelist = Element.objects.values('descr').annotate()
        context['descr'] = namelist
        context['elementsum'] = self.elementsum
        context['elementform'] = FormElement()
        context['userandproduct'] = UserAndProduct.objects.all()
        return context

@csrf_exempt
@login_required()
def add_element(request):
    if request.method == 'POST':
        descr = request.POST['descr']
        projectid = request.POST['projectid']
        moduleid = request.POST['moduleid']
        locmode = request.POST['locmode']
        location = request.POST['location']
        createat = request.user.username
        updateat = request.user.username
        mid = Module.objects.get(pk=int(moduleid))
        pid = Project.objects.get(pk=int(projectid))
        ele = Element(moduleid=mid, projectid=pid, descr=descr, locmode=locmode, location=location, createat=createat, updateat=updateat)
        ele.save()
        # return HttpResponse(descr + '@' + locmode + '@' + location + '@' + str(mid.pk))
        return HttpResponse('添加元素成功。')
    else:
        return HttpResponse('添加元素失败。')


@csrf_exempt
@login_required()
def update_element(request):
    if request.method == 'POST':
        post_dict = request.POST
        element_dict = {"id":post_dict['elementid'],
                        "descr": post_dict['eledescr'],
                        "projectid":post_dict['ele_add_projectid'],
                        "moduleid": post_dict['moduleid'],
                        "locmode": post_dict['locmode'],
                        "location": post_dict['elelocation'],
                        }
        id = element_dict.get('id')
        descr = element_dict.get('descr')
        projectid = element_dict.get('projectid')
        moduleid = element_dict.get('moduleid')
        locmode = element_dict.get('locmode')
        location = element_dict.get('location')
        updateat = request.user.username
        updatetime = timezone.now()
        e = Element.objects.filter(id=int(id))
        e.update(descr=descr, projectid=projectid,moduleid=moduleid,locmode=locmode, location=location,updateat=updateat,updatetime=updatetime)
        return HttpResponse('修改成功')
    else:
        return HttpResponse('修改失败')


@login_required()
def del_element(request, id):
    element = get_object_or_404(Element, pk=int(id))
    element.delete()
    return HttpResponseRedirect(reverse('elementlist'))


@login_required()
def get_element(request):
    elementlist = []
    projectid = request.GET['projectid']
    elelista = Element.objects.raw("select id,(select name from management_module where id= moduleid_id) as modulename,locmode,location,descr from element_element where projectid_id="+projectid)
    for i in elelista:
        element = {}
        element['moduleid'] = i.modulename
        element['key'] = i.id
        location = i.locmode + "," + i.location
        element['location'] = location
        element['value'] = "["+str(i.id)+"][" + i.modulename + "]" + i.descr
        elementlist.append(element)
    return HttpResponse(json.dumps(elementlist))


@login_required()
def set_edit_element(request):
    elementid = request.GET['elementid']
    element = Element.objects.get(pk=elementid)
    elementinfo = {}
    elementinfo['id'] = element.pk
    elementinfo['descr'] = element.descr
    elementinfo['projectid'] = element.projectid.pk
    elementinfo['moduleid'] = element.moduleid.pk
    elementinfo['locmode'] = element.locmode
    elementinfo['location'] = element.location
    elementlist = [elementinfo]
    return HttpResponse(json.dumps(elementlist))

automatic/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Default Title{% endblock %} - Ray</title>
</head>
<body>
{% include 'nav.html' %}

{% block content %}
<div>这里是默认内容，所有继承自这个模板的，如果不覆盖就显示这里的默认内容。</div>
    {% for key,value in info_dict.items %}
        {{ key }}:{{ value }}<br />
    {% endfor %}

    (zhandian):{{ info_dict.site }}<br />
    (neirong):{{ info_dict.content }}<br />
{% endblock %}
   <a href="/product/add" class="btn btn-primary">add product</a>

</body>
</html>

automatic/templates/comingsoon.html
{% extends 'frame.html' %}
{% block title %}Automagic{% endblock %}
{% block slideshow %} 
<div style="text-align:center; margin-top: 100px">
<img src="/static/images/timg.png"/>
</div>  
{% endblock %}

automatic/templates/nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Base{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'css/favicon.ico' %}">
    <link rel="shortcut icon" href="{% static 'css/favicon.ico' %}" type="image/x-icon">

    <!-- 新 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

<!-- 可选的Bootstrap主题文件（一般不用引入） -->
<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-switch.css' %}">


<link rel="stylesheet" href="{% static 'css/automagic.css' %}">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="{% static 'js/jquery.min.js' %}"></script>

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap-switch.js' %}"></script>
<script src="{% static 'js/automagic.js' %}"></script>
<script>
    function addtr() {
    //行添加
{#        debugger;#}
        var len = parseInt($("#linecounter").val())+1;

         $("#tab tbody").append('<tr id=row'+len+' name="rowstep">'
                                   +'<td>Step'+len+'</td>'
                                   +'<td><input name="descr" class="form-control" placeholder="请输入步骤描述" type="input"></td>'
                                   +'<td><select id="id_keyword" name="keyword" class="form-control mb15">{% for i in  keywordlist %}<option value="{{ i.pk }}">{{ i.kwdescr }}</option>{% endfor %}</select></td>'
                                   +'<td><input name="elementid" class="form-control" placeholder="请选择元素" type="input"></td>'
                                   +'<td><input name="inputtext" class="form-control" placeholder="" type="input"></td>'
                                   +'<td><a class="btn btn-small" onclick="deltr('+len+')">删除</a></td>'
                                   +'</tr>');


        $("#linecounter").val(len);
    }
//行删除
   function deltr(index) {
     $("tr[id='row"+index+"']").remove();//删除当前行
    }

   $(document).ready(function(){
       $.ajaxSetup({
                 data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
            });
       $('#ele_add').submit(function(){
                var descr = $("#id_descr").val();      //获得form中用户输入的descr 注意这里的descr 与你html中的id一致
                var projectid = $("#id_projectid").val(); //同上
                var moduleid = $("#id_moduleid").val(); //同上
                var locmode = $("#id_locmode").val();
                var location = $("#id_location").val();
           $.ajax({
                    type:"POST",
                    data: {descr:descr, projectid:projectid, moduleid:moduleid, locmode:locmode, location:location},
                    url: "{% url 'elementadd' %}", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                    cache: false,
                    dataType: "html",

                    success: function(result, statues, xml){
                        debugger;
                        $('#log_info').addClass('bg-success');
                        $('#log_info').css('display','block');
                        $('#log_info').html(result);
                        setTimeout("location.reload()",1500);                                        //成功时弹出view传回来的结果
                    },
                    error: function(){
                        debugger;
                        $('#log_info').addClass('bg-danger');
                        $('#log_info').css('display','block');
                        $('#log_info').html('添加失败。');
                        setTimeout("location.reload()",1500);
                    }
                });
                return false;
            });

       $('#add_keyword').submit(function () {
           var keyword = $('#keyword').val();
           var kwdescr = $('#kwdescr').val();
           $.ajax({
               type:"POST",
               data:{keyword:keyword,kwdescr:kwdescr},
               url:"{% url 'keywordadd' %}",
               cache: false,
               dataType:"html",
               success:function (result, statues,xml) {
                   // debugger;
                   $('#log_info').addClass('bg-success');
                   $('#log_info').css('display','block');
                   $('#log_info').html(result);
                   setTimeout("location.reload()",1500);
                   // alert(result);
               },
               error:function () {
                   // debugger;
                   $('#log_info').addClass('bg-danger');
                   $('#log_info').css('display','block');
                   $('#log_info').html('添加失败，关键字可能已经存在。');
                   setTimeout("location.reload()",1500);
               }
           });
           return false;
       });

       $('#case_add').submit(function () {
{#           var casedesc = $('#casedesc').val();#}
{#           var isenabled = $('#id_isenabled').prop('checked');#}
{#           var projectid = $('select[name="projectid"]').val();#}
{#           var moduleid = $('select[name="moduleid"]').val();#}
{#           var dependent = $('input[name="dependent"]').val();#}
{#           var descr = $('input[name="descr"]').val();#}
{#           var keyword = $('select[name="keyword"]').val();#}
{#           var elementid = $('input[name="elementid"]').val();#}
{#           var inputtext = $('input[name="inputtext"]').val();#}

           $.ajax({
               type:"POST",
               data: $(this).serialize(),
{#               data:{casedesc:casedesc, isenabled:isenabled, projectid:projectid, moduleid:moduleid,dependent:dependent,descr:descr,keyword:keyword,elementid:elementid,inputtext:inputtext},#}
               url:"{% url 'caseadd' %}",
               cache: false,
               dataType:"html",
               success:function (result, statues,xml) {
{#                   debugger;#}
                   $('#log_info').addClass('bg-success');
                   $('#log_info').css('display','block');
                   $('#log_info').html(result);
                   setTimeout("location.reload()",1500);
                   // alert(result);
               },
               error:function () {
{#                   debugger;#}
                   $('#log_info').addClass('bg-danger');
                   $('#log_info').css('display','block');
                   $('#log_info').html('保存失败');
                   setTimeout("$('#log_info').css('display','none');",1500);
               }
           });
           return false;
       });

       $('#case_edit').submit(function () {
           var casedesc = $('#casedesc').val();
           var isenabled = $('#id_isenabled').prop('checked');
           var projectid = $('select[name="projectid"]').val();
           var moduleid = $('select[name="moduleid"]').val();
           var dependent = $('input[name="dependent"]').val();
           var descr = $('input[name="descr"]').val();
           var keyword = $('select[name="keyword"]').val();
           var elementid = $('input[name="elementid"]').val();
           var inputtext = $('input[name="inputtext"]').val();

           $.ajax({
               type:"POST",
               data: $(this).serialize(),
{#               data:{casedesc:casedesc, isenabled:isenabled, projectid:projectid, moduleid:moduleid,dependent:dependent,descr:descr,keyword:keyword,elementid:elementid,inputtext:inputtext},#}
               url:"/case/update/{{ tcase.pk }}/",
               cache: false,
               dataType:"html",
               success:function (result, statues,xml) {
{#                   debugger;#}
                   $('#log_info').addClass('bg-success');
                   $('#log_info').css('display','block');
                   $('#log_info').html(result);
                   setTimeout("$('#log_info').css('display','none');",1500);
                   // alert(result);
               },
               error:function () {
{#                   debugger;#}
                   $('#log_info').addClass('bg-danger');
                   $('#log_info').css('display','block');
                   $('#log_info').html('保存失败');
                   setTimeout("$('#log_info').css('display','none');",1500);
               }
           });
           return false;
       });

        //产品和项目二级菜单关联
       $("#selproductid").bind("change",function(){
            var s1SelectedVal = $('#selproductid').val();

            if($(this).val()==0){
                $('#id_projectid').empty();
                return;
            }
            else {
                $.ajax({
                    type:"GET",
                    data:{'productid':s1SelectedVal},
                    url: "{% url 'getproject' %}", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                    cache: false,
                    dataType:'json',

                 success: function(result,TextStatus) {
                     $('#id_projectid').empty();
                     if (result.length > 0) {
                         for (i = 0; i < result.length; i++) {
{#                             alert(result[i].value);#}
                             $('#id_projectid').append('<option value="' + result[i].key + '">' + result[i].value + '</option>');
                         }
                     }
                 }
                });
            }
        });

       $("#selprojectid").bind("change",function(){
            var s1SelectedVal = $('#selprojectid').val();

            if($(this).val()==0){
                $('#selmoduleid').empty();
                return;
            }
            else {
                $.ajax({
                    type:"GET",
                    data:{'projectid':s1SelectedVal},
                    url: "{% url 'getmodule' %}", //后台处理函数的url 这里用的是static url 需要与urls.py中的name一致
                    cache: false,
                    dataType:'json',

                 success: function(result,TextStatus) {
                     $('#selmoduleid').empty();
                     if (result.length > 0) {
                         for (i = 0; i < result.length; i++) {
{#                              debugger;#}
{#                             alert(result[i].value);#}
                             $('#selmoduleid').append('<option value="' + result[i].key + '">' + result[i].value + '</option>');
                         }
                     }
                 }
                });
            }
        });

        });
</script>

    <link rel="stylesheet" href="{% static 'css/login-vendor.css' %}">

{#    <link rel="stylesheet" href="{% static 'css/login-app-bar.css' %}">#}

    <link rel="stylesheet" href="{% static 'css/login-app.css' %}">
</head>
<body>
<div class="ui fixed transparent main menu ng-scope" ng-dblclick="scrollToTop()" id="top-menu">
<a href="{% url 'index' %}" class="left logo item ng-scope" ng-if="USER === false" cg-jump-out-angular-href="/" target="_self" style="padding: 0px 0px;">
    <img src="{% static 'images/logo.png' %}" height="50">
</a>
<div style="left: 0px;" class="left menu ng-scope" data-ng-controller="QuickSearchController" ng-style="{'left':USER === false ? '40px':'75px'}">
  <div class="public-pages ng-scope" ng-if="USER === false" style="width: 452px;">
        <div class="normal not-login-menu">
            <div class="ui simple dropdown">
                <a href="javascript:void(0);" class="item no-arrow ng-binding">AutoMagic</a>
                <div class="menu">
                    <a class="item func-item" href="#" target="_blank">TestReport</a>
                    <a class="item func-item" href="http://172.17.3.60/" target="_blank">Git Server</a>
                </div>
            </div>
            <a href="http://172.17.3.65:8111/"  target="_blank" class="item ng-binding">TeamCity</a>
            <a href="http://172.17.3.70/testrail/ " target="_blank" class="item ng-binding">TestRail</a>
            <a href="http://172.17.3.71:8112/dashboard" target="_blank" class="item ng-binding">YouTrack</a>
        </div>

    </div>
</div>
{% if user.is_authenticated %}
    <!-- ngIf: USER -->
<!-- ngIf: USER === false -->
    <div class="right menu ng-scope" ng-if="USER === false">
        <div class="ui item mart-logo">
        </div>
        <i class="icon-user"></i>
        <button class="btn btn-link">{{ user.username }}</button>
        <a href="{% url 'auto-logout' %}" class="btn btn-link" cg-auto-refresh-href="/logout">Logout</a>
    </div>
    <!-- end ngIf: USER === false -->
    <!-- end ngIf: USER === false -->
{% else %}
    <div class="right menu ng-scope" ng-if="USER === false">
        <div class="ui item mart-logo">
        </div>
        <a href="{% url 'auto-login' %}" class="btn btn-primary " >Login</a>
    </div>
{% endif %}
</div>
{% block content %}
    <div>
{% block slideshow %}{% endblock %}
{% block page_content %}{% endblock %}
    </div>
{% endblock %}
</body>