auto_auth/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as contrib_auth_views
from django.contrib.auth.decorators import login_required
from auto_auth import views

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/profile/$', views.profile,
        name='auto-profile'),

    url(r'^register/$', views.register, name='auto-register'),

    url(r'^confirm/(?P<activation_key>[A-Za-z0-9\-]+)/$', views.confirm,
        name='auto-confirm'),

    url(r'^user/add/$', views.add_user, name='adduser'),
    url(r'^user/list/$', login_required(views.UserListIndex.as_view()), name='userlist'),
    url(r'^user/update/$', views.update_user, name='userupdate'),
    url(r'^user/del/(?P<id>\d+)/$', views.del_user, name='userdel'),
    url(r'^setedit/user/$', views.set_edit_user, name='setedituser'),

    url(r'^login/$', views.LoginViewWithCustomTemplate.as_view(), name='auto-login'),
    url(r'^logout/$',
        contrib_auth_views.LogoutView.as_view(next_page=reverse_lazy('auto-login')),
        name='auto-logout'),

    url(r'^passwordreset/$', contrib_auth_views.PasswordResetView.as_view(),
        name='auto-password_reset'),
    url(r'^passwordreset/done/$', contrib_auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^passwordreset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        contrib_auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^passwordreset/complete/$',
        contrib_auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

automatic/element/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from automatic.element import views

urlpatterns = [
    url(r'list/$', login_required(views.ElementListIndex.as_view()), name='elementlist'),
    url(r'add/$', views.add_element, name='elementadd'),
    url(r'update/$', views.update_element, name='elementupdate'),
    url(r'del/(?P<id>\d+)/$', views.del_element, name='elementdel'),
    url(r'get/$', views.get_element, name='getelement'),
    url(r'setedit/$', views.set_edit_element, name='seteditelement'),
]

automatic/keywords/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from automatic.keywords import views

urlpatterns = [
    url(r'list/$', login_required(views.KeyWordListIndex.as_view()), name='keywordlist'),
    url(r'add/$', views.add_keyword, name='keywordadd'),
    url(r'update/$', views.update_keyword, name='keywordupdate'),
    url(r'del/(?P<id>\d+)/$', views.del_keyword, name='keyworddel'),
    url(r'get/$', views.get_keyword, name='getkeyword'),
    url(r'setedit/$', views.set_edit_keyword, name='seteditelement'),
]

automatic/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include, url
from auto_auth import urls as auth_urls
from automatic.testcase import urls as case_urls
from automatic.management import urls as mgt_urls
from automatic.element import urls as ele_urls
from automatic.keywords import urls as keywords_urls
from automatic.testtask import urls as task_urls
from automatic.webinterface import urls as interf_urls
from auto_auth.views import index

urlpatterns = [
    url('^$', index),
    url('^index/', index),
    url('admin/', admin.site.urls),
    url(r'^account/', include(auth_urls)),

    url(r'^setting/', include(mgt_urls)),

    url(r'^func/case/', include(case_urls)),

    url(r'^func/element/', include(ele_urls)),

    url(r'^func/keyword/', include(keywords_urls)),

    url(r'^func/task/', include(task_urls)),

    url(r'^interface/', include(interf_urls)),



    # url(r'^interf/web/home/$',  login_required(interface.WebinterfaceListIndex.as_view()), name='webinterface'),
    # url(r'^interf/get/response/$', interface.get_response, name='getresponse'),
    # url(r'^tools/syslog/home/$', automate.page_syslog, name='toolsyslog'),
    # url(r'^tools/snmp/home/$', automate.comingsoon, name='toolsnmp'),
    # url(r'^accounts/', include(oidc_urls)),
]

automatic/management/models.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-06
"""
from __future__ import unicode_literals

import datetime
from django.db import models
from auto_auth.models import User
# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=32, verbose_name='产品名称', unique=True)
    # version = models.CharField(max_length=32)
    isenabled = models.BooleanField(default=True, blank=True, verbose_name='产品状态')
    descr = models.TextField(null=True, blank=True, verbose_name='产品描述')
    createtime = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='创建时间')
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='创建者')
    updatetime = models.DateTimeField(auto_now=True,null=True, blank=True, verbose_name='更新时间')
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='更新者')
    sortby = models.IntegerField(null=True, blank=True, editable=True, default=0, verbose_name='排序')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.createtime = datetime.datetime.now()
            self.updatetime = datetime.datetime.now()

        super(Product, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-sortby"]


class Project(models.Model):
    productid = models.ForeignKey(Product, verbose_name='产品名称', on_delete=models.CASCADE)
    name = models.CharField(max_length=32, unique=True, verbose_name='项目名称')
    version = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='版本')
    isenabled = models.BooleanField(default=True, verbose_name='状态')
    descr = models.TextField(null=True, blank=True, editable=True,verbose_name='项目描述')
    createtime = models.DateTimeField(auto_now_add=True, null=True, blank=True, editable=True,verbose_name='创建时间')
    createat = models.CharField( max_length=32, null=True, blank=True, editable=True, verbose_name='创建者')
    updatetime = models.DateTimeField(auto_now=True,null=True, blank=True, verbose_name='更新时间')
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='更新者')
    sortby = models.IntegerField(null=True, blank=True, editable=True, default=0, verbose_name='排序')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["-sortby"]


class Module(models.Model):
    projectid = models.ForeignKey(Project, verbose_name='所属项目', on_delete=models.CASCADE)
    name = models.CharField(max_length=32, verbose_name='模块名称')
    isenabled = models.BooleanField(default=True, verbose_name='状态')
    createtime = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    createat = models.CharField(max_length=32 ,null=True, blank=True, editable=True, verbose_name='创建者')
    updatetime = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True, verbose_name='更新者')
    sortby = models.IntegerField(null=True, blank=True, editable=True, default=0, verbose_name='排序')

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["-sortby"]

class UserAndProduct(models.Model):
    username = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    productname = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

automatic/testcase/models.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-06
"""
from django.db import models
from automatic.management.models import Project, Module
from automatic.keywords.models import Keyword
from automatic.element.models import Element
# from django.core.validators import validate_comma_separated_integer_list
# Create your models here.


class Case(models.Model):
    projectid = models.ForeignKey(Project, on_delete=models.DO_NOTHING)
    moduleid = models.ForeignKey(Module, on_delete=models.DO_NOTHING)
    testrailcaseid = models.CharField(max_length=12,null=True, blank=True, editable=True)
    casedesc = models.CharField(max_length=255, verbose_name="Title")
    isenabled = models.BooleanField(default=True)
    issmoke = models.BooleanField(default=False)
    dependent = models.CharField(max_length=8,null=True, blank=True, editable=True)
    debuginfo = models.CharField(max_length=9999, null=True, blank=True, editable=True)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32,null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now_add=True)
    updateat = models.CharField(max_length=32,null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.casedesc

# class Caseset(models.Model):
#     descr = models.CharField(max_length=200)
#     caseid = models.CharField(validators=[validate_comma_separated_integer_list],max_length=255)
#     isenabled = models.BooleanField(default=True)
#     createtime = models.DateTimeField(auto_now_add=True)
#     createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
#     updatetime = models.DateTimeField(auto_now=True)
#     updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)
#
#     def __unicode__(self):
#         return self.descr


class Step(models.Model):
    caseid = models.ForeignKey(Case, on_delete=models.CASCADE)
    stepid = models.IntegerField(null=True, blank=True, editable=True)
    descr = models.CharField(max_length=200, null=True, blank=True, editable=True)
    keywordid = models.ForeignKey(Keyword, on_delete=models.DO_NOTHING)
    elementid = models.ForeignKey(Element,null=True, blank=True, on_delete=models.DO_NOTHING)
    inputtext = models.CharField(max_length=200, null=True, blank=True, editable=True)
    createtime = models.DateTimeField(auto_now_add=True)
    createat = models.CharField(max_length=32, null=True, blank=True, editable=True)
    updatetime = models.DateTimeField(auto_now=True)
    updateat = models.CharField(max_length=32, null=True, blank=True, editable=True)

    def __unicode__(self):
        return self.descr

automatic/element/forms.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-08
"""
from django import forms
from automatic.element.models import Element
from django.forms import ModelForm, Textarea, Select, TextInput


class FormElement(forms.ModelForm):
    class Meta:
        model = Element
        fields = ('descr','projectid','moduleid','locmode','location')
        widgets = {'locmode': Select(attrs={'class':'ak-left ac-aselect','required':''}),
                   'descr':TextInput(attrs={'class':'form-control','placeholder':'请输入元素描述','required':''}),
                   'location': TextInput(attrs={'class': 'form-control','placeholder':'（如：id_username）','required':''}),
                   }

automatic/testcase/forms.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-06
"""
from django import forms
from automatic.testcase.models import *


class FormCase(forms.ModelForm):
    class Meta:
        model = Case
        fields = ('casedesc','testrailcaseid','projectid','moduleid','isenabled','dependent')


class FormStep(forms.ModelForm):
    class Meta:
        model = Step
        fields = ('caseid', 'descr', 'keywordid','elementid','inputtext')

automatic/element/views.py
# -*- coding:utf-8 -*-
"""
__author__ = 'Ray'
mail:tsbc@vip.qq.com
2020-01-08
"""
import json
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from automatic.element.forms import *
from django.views.generic import ListView
from automatic.element.models import *
from django.db.models import Q
from django.urls import reverse
from automatic.management.models import Project, UserAndProduct
from automatic.element.models import Element

# Create your views here.


class ElementListIndex(ListView):
    context_object_name = 'elementlist'
    template_name = 'element/element.html'
    paginate_by = 10
    elementsum = 0
    model = Element
    http_method_names = [u'get']

    def get_queryset(self):
        prodcutid = UserAndProduct.objects.filter(username=self.request.user).values('productname')
        elementlist = Element.objects.filter(projectid__in=Project.objects.filter(productid__in=prodcutid).values('id')).order_by('-pk')
        prodcutid = self.request.GET.get('check_productname')
        projectid = self.request.GET.get('projectid')
        moduleid = self.request.GET.get('moduleid')
        keyword = self.request.GET.get('keyword')
        if prodcutid and int(prodcutid):
            elementlist = elementlist.filter(projectid__in=Project.objects.filter(productid=prodcutid).values('id'))
        if projectid:
            elementlist = elementlist.filter(projectid=projectid)
        if moduleid:
            elementlist = elementlist.filter(moduleid=moduleid)
        if keyword:
            elementlist = elementlist.filter(Q(id__icontains=keyword)|Q(location__icontains=keyword)|Q(descr__icontains=keyword))
        self.elementsum = len(elementlist)
        return  elementlist

    def get_context_data(self, **kwargs):
        context = super(ElementListIndex,self).get_context_data(**kwargs)
        namelist = Element.objects.values('descr').annotate()
        context['descr'] = namelist
        context['elementsum'] = self.elementsum
        context['elementform'] = FormElement()
        context['userandproduct'] = UserAndProduct.objects.all()
        return context

@csrf_exempt
@login_required()
def add_element(request):
    if request.method == 'POST':
        descr = request.POST['descr']
        projectid = request.POST['projectid']
        moduleid = request.POST['moduleid']
        locmode = request.POST['locmode']
        location = request.POST['location']
        createat = request.user.username
        updateat = request.user.username
        mid = Module.objects.get(pk=int(moduleid))
        pid = Project.objects.get(pk=int(projectid))
        ele = Element(moduleid=mid, projectid=pid, descr=descr, locmode=locmode, location=location, createat=createat, updateat=updateat)
        ele.save()
        # return HttpResponse(descr + '@' + locmode + '@' + location + '@' + str(mid.pk))
        return HttpResponse('添加元素成功。')
    else:
        return HttpResponse('添加元素失败。')


@csrf_exempt
@login_required()
def update_element(request):
    if request.method == 'POST':
        post_dict = request.POST
        element_dict = {"id":post_dict['elementid'],
                        "descr": post_dict['eledescr'],
                        "projectid":post_dict['ele_add_projectid'],
                        "moduleid": post_dict['moduleid'],
                        "locmode": post_dict['locmode'],
                        "location": post_dict['elelocation'],
                        }
        id = element_dict.get('id')
        descr = element_dict.get('descr')
        projectid = element_dict.get('projectid')
        moduleid = element_dict.get('moduleid')
        locmode = element_dict.get('locmode')
        location = element_dict.get('location')
        updateat = request.user.username
        updatetime = timezone.now()
        e = Element.objects.filter(id=int(id))
        e.update(descr=descr, projectid=projectid,moduleid=moduleid,locmode=locmode, location=location,updateat=updateat,updatetime=updatetime)
        return HttpResponse('修改成功')
    else:
        return HttpResponse('修改失败')


@login_required()
def del_element(request, id):
    element = get_object_or_404(Element, pk=int(id))
    element.delete()
    return HttpResponseRedirect(reverse('elementlist'))


@login_required()
def get_element(request):
    elementlist = []
    projectid = request.GET['projectid']
    elelista = Element.objects.raw("select id,(select name from management_module where id= moduleid_id) as modulename,locmode,location,descr from element_element where projectid_id="+projectid)
    for i in elelista:
        element = {}
        element['moduleid'] = i.modulename
        element['key'] = i.id
        location = i.locmode + "," + i.location
        element['location'] = location
        element['value'] = "["+str(i.id)+"][" + i.modulename + "]" + i.descr
        elementlist.append(element)
    return HttpResponse(json.dumps(elementlist))


@login_required()
def set_edit_element(request):
    elementid = request.GET['elementid']
    element = Element.objects.get(pk=elementid)
    elementinfo = {}
    elementinfo['id'] = element.pk
    elementinfo['descr'] = element.descr
    elementinfo['projectid'] = element.projectid.pk
    elementinfo['moduleid'] = element.moduleid.pk
    elementinfo['locmode'] = element.locmode
    elementinfo['location'] = element.location
    elementlist = [elementinfo]
    return HttpResponse(json.dumps(elementlist))

automatic/templates/testcase/caseadd.html
{% extends 'frame.html' %}
{% block title %}Automagic{% endblock %}
{% block slideshow %}
    <div class="ak-zper-midbox ak-jsch-mid">
         <div class="ak-zper-inbox-title ak-jsch-title clearfix">
               <div class="ak-left ak-jsch-row3 ak-zper-fix-btnbox">
                    <span class="ak-zper-remindback"></span>
                    <span class="inbox-text">添加用例</span>
               </div>
             <div id="log_info" class="ac-addtips"></div>
            <select id="selproductid" name="caseproductname" class="ak-right ak-left ac-aselect ac-margint8">
                      <option value="0">-产品名称-</option>
                          {% for product in userandproduct  %}
                              {% if product.username == request.user %}
                                  <option value="{{ product.productname.id }}" {% if request.GET.productname  == product.productname.name %}selected{% endif %}>{{ product.productname.name }}</option>
                              {% endif %}
                          {% endfor %}
                </select>

          </div>

      	  <div class="col-md-12">
 <form method='post'  id="case_add">
    {% csrf_token %}
    <div class="ak-jsch-modal-row col01">
        <div class="ak-jsch-pos">
            <div class="ak-jsch-point">
            </div>
        </div>
        <div class="ak-jsch-modal-text col01 clearfix">
            <span class="ak-jsch-item-left ak-left ">用例描述</span>
            <div class="ak-jsch-item-right col02 ak-left">
                <input id="casedesc" name="casedesc" class="ak-jsch-modal-input" type="text" required="" placeholder="测试用例描述">
            </div>
        </div>
    </div>
     <div class="ak-jsch-modal-row col01 ak-jsch-padding">
         <div class="ak-jsch-modal-text">
             <div class="ak-jsch-modal-item clearfix"><span class="ak-left ak-jsch-item-left ">状态</span>
                 <div class="sky-form col01 ak-left ac-ml10">
                     <label class="toggle">
                         <input type="checkbox" id="id_isenabled" name="isenabled" checked="checked">
                         <i class="rounded-4x ak-aoffon-btn"></i>
                     </label>
                 </div>
             </div>
             <div class="ak-jsch-modal-item ak-jsch-pt clearfix">
                 <span class="ak-jsch-item-left ak-left">项目</span>
                 <div class="ak-jsch-item-right ak-left">
                     <select id="selprojectid" name="projectid" class="ak-left ac-aselect col01" required=""></select>
                 </div>
             </div>
             <div class="ak-jsch-modal-item ak-jsch-pt clearfix">
                 <span class="ak-jsch-item-left ak-left">模块</span>
                 <div class="ak-jsch-item-right ak-left">
                     <select id="selmoduleid" name="moduleid" class="ak-left ac-aselect col01" required=""><option value="">所属模块</option></select>
                 </div>
             </div>
             <div class="ak-jsch-modal-item clearfix"><span class="ak-left ak-jsch-item-left ">冒烟测试</span>
                 <div class="sky-form col01 ak-left ac-ml10">
                     <label class="toggle">
                         <input type="checkbox" id="id_issmoke" name="issmoke">
                         <i class="rounded-4x ak-aoffon-btn"></i>
                     </label>
                 </div>
             </div>
             <div class="ak-jsch-modal-item ak-jsch-pt clearfix">
                 <span class="ak-jsch-item-left ak-left">依赖用例</span>
                 <div class="ak-jsch-item-right ak-left">
                     <input id="id_dependent" name="dependent" type="text" placeholder="请输入依赖用例的编号" class="ac-acaseedit-input" />
                 </div>
             </div>
{#            <div class="ak-jsch-modal-item ak-jsch-pt clearfix">#}
{#                 <span class="ak-jsch-item-left ak-left ac-acase-desc">TestRail ID</span>#}
{#                 <div class="ak-jsch-item-right ak-left">#}
{#                     <input id="id_testrailcaseid" name="testrailcaseid" type="text" placeholder="关联TestRail的用例编号" class="ac-acaseedit-input" />#}
{#                 </div>#}
{#             </div>#}
             <table class="table table-conde" id="tab" style="width:100%">
                 <caption class="text-left">
                    <button type="button" onclick="case_step_addtr();" class="text-left ac-btn-addcase orange ac-margin-tb15">添加一行</button>
                     <input class="ac-acaseedit-input" id="rowid" value="" type="number" placeholder="添加到第N行之后">
                 </caption>
                 <thead>
                 <th>Step No</th>
                 <th>Step Descr</th>
                 <th>Keyword</th>
                 <th>Element</th>
                 <th>Input</th>
                 <th>操作</th>
                 <input hidden="true" id="linecounter"   value = 1 type='text' >
                 </thead>
                 <tbody>
                 <tr id="row1">
                     <td>1</td>
                     <td><input name="descr" class="ac-acaseedit-input" placeholder="请输入步骤描述" type="input" required=""></td>
                     <td><select id="keyword_1" name="keyword" class="ak-left ac-aselect col01" required=""></select></td>
                     <td>
{#                         <select id="id_elementid" name="elementid" class="ak-left ac-aselect col01"><option value="None">请选择可用元素</option></select>#}
                         <input id="autocomplete_1" name="autocomplete" class="ui-autocomplete-input ac-element-input" type="input"><input type="hidden" id="elementid_1" name="elementid" value="None">
                     </td>
                     <td><input name="inputtext" class="ac-keywordtext-input" placeholder="" type="input" ></td>
                     <td></td>
                 </tr>
                 </tbody>
                 <tfoot class="text-left">

                 </tfoot>
             </table>
             <button type="button" onclick="case_step_addtr();" class="text-left ac-btn-addcase orange ac-margin-tb15">添加一行</button>
             <div style="text-align: center;">
                <input  class="btn btn-sm btn-primary" type="submit" value="提交">
                <input class="btn btn-sm btn-default" type="reset" value="重置">
                 <button onclick="goback();" class="btn btn-sm btn-success" role="button">取消>></button>
             </div>
            <div></div>
         </div>
     </div>
     <div><br><br></div>
 </form>
          </div>
    </div>
{% endblock %}
{% block script %}
{% load static %}
<script type="text/javascript" src="{% static 'js/casemanage.js' %}"></script>
{% endblock %}

automatic/templates/testcase/caselist.html
{% extends 'nav.html' %}
{% block title %}Case List{% endblock %}
{% block slideshow %}
    <br/><br/><br/>
    <form class="form-inline" role="form" action="" method="GET">
    {% if caselist %}
        <div class="panel panel-default">
    <div class="panel-heading">
          <div class="form-group">
            <select name="projectid" class="form-control">
              <option value="">所属项目</option>
              {% for i in caselist %}
                 <option value="{{ i.projectid }}" {% if request.GET.projectid  == i.projectid %}selected{% endif %}>{{ i.projectid }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <select name="moduleid" class="form-control">
              <option value="">模 块</option>
              {% for i in caselist %}
                    <option value="{{ i.moduleid }}" {% if request.GET.modulename  == i.moduleid %}selected{% endif %}>{{ i.moduleid }}</option>
                {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <select name="casestatus" class="form-control">
              <option value="">状态</option>
                 <option value="True" >启用</option>
                 <option value="False" >禁用</option>
            </select>
          </div>
          <div class="form-group">
          <input type="input" name="keyword" class="form-control" placeholder="Please input Keyword" value="{{ request.GET.keyword }}">
          </div>
          <button type="submit" class="btn btn-primary">Search</button>
        <div align="right" class="form-group"><a href="/case/add/" class="btn btn-primary">Add Case</a></div>
      </div>
        <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
          <tr>
              <th>Case ID</th>
              <th>Module Name</th>
              <th>Case Descr</th>
              <th>Case Status</th>
              <th>Create At</th>
              <th>Create Time</th>
              <th>UpdateAt</th>
              <th>Update Time</th>
          <th></th>
          </tr>
        </thead>
        <tbody>
          {% for case in caselist %}
            <tr>
                <td>{{ case.id }}</td>
                <td>{{ case.moduleid.name }}</td>
                <td><a href="{% url 'caseview' case.id %}"/> {{ case.casedesc }}</td>
                <td>{{ case.isenabled }}</td>
                <td>{{ case.createat }}</td>
                <td>{{ case.createtime|date:'Y-m-d H:i:s' }}</td>
                <td>{{ case.createat }}</td>
                <td>{{ case.updatetime|date:'Y-m-d H:i:s' }}</td>
                <th>
                    <a href="{% url 'caseupdate' case.id %}" class="btn btn-primary" role="button">Edit</a>
                    <a href="{% url 'casedel' case.id %}" class="btn btn-primary" role="button" onclick="return confirm('Are you Sure Deleted.')">Delete</a>
                </th>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
        {% if is_paginated %}
        <div class="panel-default">
        <ul class="pagination">
          <li><a href="{{ request.path }}?page=1">«</a></li>
          {% if page_obj.has_previous %}
            <li><a href="{{ request.path }}?&page={{ page_obj.previous_page_number }}">上一页</a></li>
          {% else %}
            <li class="previous disabled"><a>上一页</a></li>
          {% endif %}
          {% for i in page_obj.paginator.page_range %}
            <li {% if page_obj.number == i %}class="active"{% endif %}><a href="{{ request.path }}?page={{ i }}">{{ i }}</a></li>
          {% endfor %}
          {% if page_obj.has_next %}
            <li><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">下一页</a></li>
          {% else %}
            <li class="previous disabled"><a>下一页</a></li>
          {% endif %}
          <li><a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">»</a></li>
            <li><span>This is {{ page_obj.number }}</span></li>
        </ul>
    </div>
        {% endif %}
    {% else %}
        <p> No msg!!!</p>
    {% endif %}
  </form>
{% endblock %}